data = {
  const nodes = [
    { name: "pool" },
    { name: "R6自由民主党" },
    { name: "R6立憲民主党" },
    { name: "R6日本維新の会" },
    { name: "R6日本共産党" },
    { name: "R6国民民主党" },
    { name: "R6参政党" },
    { name: "R6日本保守党" },
    { name: "R6社会民主党" },
    { name: "R6公明党" },
    { name: "R6れいわ新選組" },
    { name: "R6みんなでつくる党" },
    { name: "R6安楽死制度を考える会" },
    { name: "R6諸派" },
    { name: "R6無所属" },
    { name: "R7自由民主党" },
    { name: "R7国民民主党" },
    { name: "R7参政党" },
    { name: "R7立憲民主党" },
    { name: "R7公明党" },
    { name: "R7日本維新の会" },
    { name: "R7れいわ新選組" },
    { name: "R7日本保守党" },
    { name: "R7日本共産党" },
    { name: "R7チームみらい" },
    { name: "R7社会民主党" },
    { name: "R7NHK党" },
    { name: "R7再生の道" },
    { name: "R7日本誠真会" },
    { name: "R7無所属連合" },
    { name: "R7日本改革党" }
  ];
  const links = [
    { source: "R6自由民主党", target: "pool", value: 20867762 },
    { source: "R6立憲民主党", target: "pool", value: 15740860 },
    { source: "R6日本維新の会", target: "pool", value: 6048103 },
    { source: "R6日本共産党", target: "pool", value: 3695806 },
    { source: "R6国民民主党", target: "pool", value: 2349583 },
    { source: "R6参政党", target: "pool", value: 1870347 },
    { source: "R6日本保守党", target: "pool", value: 1145622 },
    { source: "R6社会民主党", target: "pool", value: 934598 },
    { source: "R6公明党", target: "pool", value: 730401 },
    { source: "R6れいわ新選組", target: "pool", value: 425445 },
    { source: "R6みんなでつくる党", target: "pool", value: 23784 },
    { source: "R6安楽死制度を考える会", target: "pool", value: 18455 },
    { source: "R6諸派", target: "pool", value: 199592 },
    { source: "R6無所属", target: "pool", value: 2534571 },
    { source: "pool", target: "R7自由民主党", value: 12808306 },
    { source: "pool", target: "R7国民民主党", value: 7620492 },
    { source: "pool", target: "R7参政党", value: 7425053 },
    { source: "pool", target: "R7立憲民主党", value: 7397457 },
    { source: "pool", target: "R7公明党", value: 5210569 },
    { source: "pool", target: "R7日本維新の会", value: 4375927 },
    { source: "pool", target: "R7れいわ新選組", value: 3879914 },
    { source: "pool", target: "R7日本保守党", value: 2982093 },
    { source: "pool", target: "R7日本共産党", value: 2864738 },
    { source: "pool", target: "R7チームみらい", value: 1517890 },
    { source: "pool", target: "R7社会民主党", value: 1217823 },
    { source: "pool", target: "R7NHK党", value: 682626 },
    { source: "pool", target: "R7再生の道", value: 524787 },
    { source: "pool", target: "R7日本誠真会", value: 333263 },
    { source: "pool", target: "R7無所属連合", value: 289222 },
    { source: "pool", target: "R7日本改革党", value: 55232 }
  ];
  return { nodes, links };
};
